linuxdeepin/deepin-service-manager

README.md
README.zh_CN.md

doc: update README

---

debian/changelog
debian/control

chore: change debian source name

---

misc/CMakeLists.txt
misc/org.deepin.ServiceManager1.conf

fix(manager): cannot register system dbus 

---

src/core/service/serviceqtdbus.cpp
src/core/service/servicesdbus.cpp
src/deepin-service-manager/groupmanager.cpp
src/deepin-service-manager/groupmanager.h
src/deepin-service-manager/main.cpp
src/deepin-service-manager/pluginloader.cpp
src/deepin-service-manager/pluginloader.h
src/deepin-service-manager/pluginmanager.cpp
src/deepin-service-manager/pluginmanager.h
src/deepin-service-manager/servicemanager.cpp
src/deepin-service-manager/servicemanager.h

feat: support load one plugin

---

src/deepin-service-manager/utils.h

chore: update group manager interface

---

src/core/policy/policy.cpp
src/core/policy/policy.h
src/core/service/serviceqtdbus.cpp
src/core/service/servicesdbus.cpp
src/deepin-service-manager/pluginloader.cpp

chore: update policy field

---

misc/CMakeLists.txt
misc/deepin-service-group@.service
misc/deepin-service-plugin@.service
src/deepin-service-manager/servicemanager.cpp

feat: dbus service contact to systemd service

---

develop-guide.md

chore: update develop-guide

---

src/demo/plugin-qt/demo1/plugin.cpp
src/demo/plugin-qt/demo2/plugin.cpp

fix(demo): rm build warning

---

src/core/service/servicesdbus.cpp

No need to determine if QLibrary is loaded
Log:

fix(sdbus): cannot register sdbus plugin

---

src/demo/CMakeLists.txt

chore(demo): add cmake option for demo

---

src/core/policy/policy.cpp
src/core/service/qtdbushook.cpp
src/core/service/serviceqtdbus.cpp
src/core/service/servicesdbus.cpp
src/deepin-service-manager/main.cpp
src/deepin-service-manager/pluginloader.cpp
src/deepin-service-manager/pluginmanager.cpp
src/deepin-service-manager/servicemanager.cpp
src/deepin-service-manager/servicemanagerprivate.cpp

1. use qt category
2. adjust some log level
Log:

refactor(log): optimize log printing

---

src/core/service/servicesdbus.cpp

refactor(log): print error message from errno for `servicesdbus`

---

src/core/service/servicesdbus.cpp

fix(sdbus): judge session bus or system bus

---

src/core/service/serviceqtdbus.cpp
src/core/service/servicesdbus.cpp

chore(service): add library error message log

---

debian/deepin-service-manager.install
debian/libdeepin-service-framework-dev.install
debian/libdeepin-service-framework.install

For other plugins, we need more precise matching in `install` file.
Log:

chore(debian): more precise matching

---

LICENSES/MIT.txt
debian/control
debian/deepin-service-plugin-oom.install
debian/rules
src/plugin-sdbus/CMakeLists.txt
src/plugin-sdbus/plugin-oom/3rdparty/earlyoom/globals.c
src/plugin-sdbus/plugin-oom/3rdparty/earlyoom/globals.h
src/plugin-sdbus/plugin-oom/3rdparty/earlyoom/kill.c
src/plugin-sdbus/plugin-oom/3rdparty/earlyoom/kill.h
src/plugin-sdbus/plugin-oom/3rdparty/earlyoom/meminfo.c
src/plugin-sdbus/plugin-oom/3rdparty/earlyoom/meminfo.h
src/plugin-sdbus/plugin-oom/3rdparty/earlyoom/msg.c
src/plugin-sdbus/plugin-oom/3rdparty/earlyoom/msg.h
src/plugin-sdbus/plugin-oom/CMakeLists.txt
src/plugin-sdbus/plugin-oom/dconfig-plugin-oom.json
src/plugin-sdbus/plugin-oom/dconfig.c
src/plugin-sdbus/plugin-oom/dconfig.h
src/plugin-sdbus/plugin-oom/oom.c
src/plugin-sdbus/plugin-oom/oom.h
src/plugin-sdbus/plugin-oom/org.deepin.oom1.conf
src/plugin-sdbus/plugin-oom/plugin-oom.json
src/plugin-sdbus/plugin-oom/plugin.c
src/plugin-sdbus/plugin-oom/service.c
src/plugin-sdbus/plugin-oom/service.h

feat: add plugin-oom

---

.clang-format

chore: add `.clang-format`

---

src/core/service/qtdbushook.cpp
src/core/service/servicesdbus.cpp

1.添加sdbus的权限管控支持
2.统一qt dbus与sdbus错误返回
Log:

feat: support dbus permission manager

---

src/plugin-sdbus/plugin-oom/dconfig.c

chore: correct a typo in dconfig.c

---

misc/CMakeLists.txt
misc/deepin-service-group@.service.in
misc/deepin-service-manager.service.in
misc/deepin-service-plugin@.service.in

1.
由于service-manager与service-group自动enable，并且不希望被用户disable,所以去掉 Install 节点
2. 在 User 级别的服务加上Slice=session.slice, 让其在用户退出是自动退出
Log:

fix(systemd): cannot exit when all user logout

---

src/core/service/serviceqtdbus.cpp

fix(qtdbus): first time cannot such object path

---

misc/deepin-service-group@.service.in
misc/deepin-service-manager.service.in
misc/deepin-service-plugin@.service.in

加固 dbus 进程
Task: https://pms.uniontech.com/task-view-361197.html

chore: systemd hardening

---

debian/changelog

chore: bump version to  1.0.4

---

misc/CMakeLists.txt
misc/deepin-service-group@.service.in
misc/deepin-service-manager.service.in
misc/deepin-service-plugin@.service.in
src/deepin-service-manager/CMakeLists.txt
src/deepin-service-manager/main.cpp

chore: 支持qt插件使用gui，解决崩溃问题

---

misc/deepin-service-group@.service.in
misc/deepin-service-manager.service.in

当服务短时间内异常重启5次，则不再重启
Log: 限制服务异常启动次数
pms: TASK-368609

feat: 限制服务异常启动次数

---

src/deepin-service-manager/main.cpp
src/deepin-service-manager/utils.cpp
src/deepin-service-manager/utils.h

启动时修改进程名称
Log:
pms: TASK-367865

feat: service-manager进程名称优化

---

debian/changelog

bump version 1.0.9
log: as title

chore: bump version 1.0.9

---

CMakeLists.txt
debian/control
debian/rules
src/core/CMakeLists.txt
src/deepin-service-manager/CMakeLists.txt
src/demo/hook-demo/CMakeLists.txt
src/demo/libqdbusservice-demo/CMakeLists.txt
src/demo/plugin-qt/demo1/CMakeLists.txt
src/demo/plugin-qt/demo2/CMakeLists.txt
src/demo/plugin-sdbus/CMakeLists.txt
src/demo/plugin-sdbus/demo1/CMakeLists.txt
src/libqdbusservice/CMakeLists.txt
tests/CMakeLists.txt

as title
Log: as title
Pms: story-37185

chore: adapt to Qt6.8

---

src/core/CMakeLists.txt

fix: Arm64 platform compilation failed

---

src/deepin-service-manager/pluginloader.cpp
src/deepin-service-manager/pluginloader.h
src/deepin-service-manager/utils.cpp
src/deepin-service-manager/utils.h

chore: check Qt type plugin Qt-Version

---

develop-guide.md
src/core/policy/policy.cpp
src/core/policy/policy.h
src/core/service/qtdbushook.cpp
src/core/service/servicesdbus.cpp
src/demo/libqdbusservice-demo/sdk-demo.json
src/demo/plugin-qt/demo2/plugin-qt-demo2.json
src/demo/plugin-sdbus/demo1/plugin-sdbus-demo1.json

Using /proc/pid/cmdline is unsafe and meaningless
Log: as title
Pms: TASK-380689

chore: Remove insecure and ineffective authority control
